services:
  webserver:
    build: docker/nginx
    container_name: ${APP}-webserver
    working_dir: /mnt/api
    volumes:
      - ./api:/mnt/api
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${APP_PORT}:80"
    depends_on:
      - php

  php:
    build: docker/php
    container_name: ${APP}-php
    working_dir: /mnt/api/
    env_file:
      - ./.env
    volumes:
      - ./api:/mnt/api/
      - ./docker/php/php-ini-overrides.local.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini
      - .env:/mnt/api/.env
    environment:
      ALPINE_VERSION: ${ALPINE_VERSION}
      COMPOSER_VERSION: ${COMPOSER_VERSION}
      PHP_IDE_CONFIG: "serverName=Records"
  
  database:
    image: mysql:8.0.42
    container_name: ${APP}-database
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=records
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3308:3306"
    volumes:
      - ./data/volumes/mysql:/var/lib/mysql
      - ./docs/sql/:/docker-entrypoint-initdb.d/
